/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/src/lib/utils.ts",
      type: "registry:lib",
    }],
  },
  "use-controllable-state": {
    name: "use-controllable-state",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-layout-effect.tsx",
      type: "registry:hook",
    },{
      path: "src/registry/src/hooks/use-controllable-state.ts",
      type: "registry:hook",
    }],
  },
  "theme-switcher": {
    name: "theme-switcher",
    description: "A theme switcher component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "src/registry/theme-switcher/theme-switcher.tsx",
      type: "registry:component",
    }],
  },
  "flip-sentences": {
    name: "flip-sentences",
    description: "",
    type: "registry:component",
    files: [{
      path: "src/registry/flip-sentences/flip-sentences.tsx",
      type: "registry:component",
    }],
  },
  "apple-hello-effect": {
    name: "apple-hello-effect",
    description: "Create a Xin chào and Hello writing effect inspired by Apple using Motion for React.",
    type: "registry:component",
    files: [{
      path: "src/registry/apple-hello-effect/apple-hello-effect.tsx",
      type: "registry:component",
    }],
  },
  "wheel-picker": {
    name: "wheel-picker",
    description: "iOS-like wheel picker for React with smooth inertia scrolling and infinite loop support.",
    type: "registry:component",
    files: [{
      path: "src/registry/wheel-picker/wheel-picker.tsx",
      type: "registry:component",
    }],
  },
  "work-experience": {
    name: "work-experience",
    description: "Displays a list of work experiences with role details and durations.",
    type: "registry:component",
    files: [{
      path: "src/registry/work-experience/work-experience.tsx",
      type: "registry:component",
    }],
  },
  "wheel-picker-block-01": {
    name: "wheel-picker-block-01",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/wheel-picker-demo.tsx",
      type: "registry:component",
    }],
  },
  "wheel-picker-block-02": {
    name: "wheel-picker-block-02",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/wheel-picker-form-demo.tsx",
      type: "registry:component",
    }],
  },
  "work-experience-block-01": {
    name: "work-experience-block-01",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/work-experience-demo.tsx",
      type: "registry:component",
    }],
  },
  "apple-hello-effect-vi-demo": {
    name: "apple-hello-effect-vi-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-vi-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/apple-hello-effect-vi-demo.tsx")),
  },
  "apple-hello-effect-en-demo": {
    name: "apple-hello-effect-en-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/apple-hello-effect-en-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/apple-hello-effect-en-demo.tsx")),
  },
  "theme-switcher-demo": {
    name: "theme-switcher-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-switcher-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/theme-switcher-demo.tsx")),
  },
  "wheel-picker-demo": {
    name: "wheel-picker-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/wheel-picker-demo.tsx")),
  },
  "wheel-picker-form-demo": {
    name: "wheel-picker-form-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/wheel-picker-form-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/wheel-picker-form-demo.tsx")),
  },
  "work-experience-demo": {
    name: "work-experience-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/work-experience-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/work-experience-demo.tsx")),
  },
  "intent-classification-demo": {
    name: "intent-classification-demo",
    description: "Interactive demo of AI-powered intent classification system",
    type: "registry:example",
    files: [{
      path: "src/components/intent-classification-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/components/intent-classification-demo").then(mod => ({ default: mod.IntentClassificationDemo }))),
  },
  "marketing-segmentation-demo": {
    name: "marketing-segmentation-demo",
    description: "Interactive demo of customer segmentation and marketing campaign system",
    type: "registry:example",
    files: [{
      path: "src/components/marketing-segmentation-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/components/marketing-segmentation-demo").then(mod => ({ default: mod.MarketingSegmentationDemo }))),
  },
  "unified-inbox-demo": {
    name: "unified-inbox-demo",
    description: "Interactive demo of unified inbox system consolidating messages from multiple channels",
    type: "registry:example",
    files: [{
      path: "src/components/unified-inbox-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/components/unified-inbox-demo").then(mod => ({ default: mod.UnifiedInboxDemo }))),
  },
  "appointment-booking-demo": {
    name: "appointment-booking-demo",
    description: "Interactive demo of AI-powered appointment booking system with automated scheduling",
    type: "registry:example",
    files: [{
      path: "src/components/appointment-booking-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/components/appointment-booking-demo").then(mod => ({ default: mod.AppointmentBookingDemo }))),
  },
}